function data()
return {
    "Vulica Franciška Skaryny",
    "Vulica Kastusia Kalinoŭskaha",
    "Vulica Anki Kupały",
    "Vulica Akuba Kołasa",
    "Vulica Maksima Bahdanoviča",
    "Vulica Vasila Bykava",
    "Vulica Iefrasińni Połackaj",
    "Vulica Paŭluka Bahryma",
    "Vulica Vincuka Viačorki",
    "Vulica Symona Budnaha",
    "Vulica Vacłava Łastoŭskaha",
    "Vulica Alesia Haruna",
    "Vulica Adama Mickieviča",
    "Vulica Źmitraka Biaduli",
    "Vulica Ivana Mieleža",
    "Vulica Ullany Radzivił",
    "Vulica Łieanida Biaduli",
    "Vulica Kiryła Turaŭskaha",
    "Vulica Siarhieia Pałuiana",
    "Vulica Łarysy Hieniiuš",
    "Vulica Branisłava Taraškieviča",
    "Vulica Advihina Š.",
    "Vulica Antona Łuckieviča",
    "Vulica Natalli Arsieńnievaj",
    "Vulica Mikoły Husoŭskaha",
    "Vulica Todara Klaštornaha",
    "Vulica Valancina Taŭłaia",
    "Vulica Michasia Čarota",
    "Vulica Pimena Pančanki",
    "Vulica Haŭryły Hareckaha",
    "Vulica Ŭładzimira Karatkieviča",
    "Vulica Łiavona Barazny",
    "Vulica Niła Hileviča",
    "Vulica Anatola Sysa",
    "Vulica Ivana Šamiakina",
    "Vulica Ŭładzimira Mulavina",
    "Vulica Azepa Drazdoviča",
    "Vulica Barysa Kita",
    "Vulica Hienadzia Buraŭkina",
    "Vulica Ihnata Damiejki",
    "Vulica Vitala Volskaha",
    "Vulica Ana Barščeŭskaha",
    "Vulica Aŭchima Karskaha",
    "Vulica Hanny Šaŭčenki",
    "Vulica Flory Baranoŭskaj",
    "Vulica Piatra Bitela",
    "Vulica Lva Sapiehi",
    "Vulica Zośki Vieras",
    "Vulica Zinaidy Bandarenki",
    "Vulica Anatola Biełaha",
    "Vulica Viktara Karamazava",
    "Vulica Aŭhiena Hlebava",
    "Vulica Antona Ahinskaha",
    "Vulica Michaiła Ptašuka",
    "Vulica Ivana Nosoviča",
    "Vulica Michasia Stralcova",
    "Vulica Ryhora Baradulina",
    "Vulica Arkadzia Smoliča",
    "Vulica Aleny Sapiehi",
    "Vulica Hanny Volskaj",
    "Vulica Adama Hłobusa",
    "Vulica Viktara Rakickaha",
    "Vulica Spakojnaia",
    "Vulica Viasiołkavaia",
    "Vulica Ručaj",
    "Vulica Soniečnaia",
    "Vulica Łiasnaia",
    "Vulica Zornaia",
    "Vulica Paleskaia",
    "Vulica Kvietkavaia",
    "Vulica Asnaia",
    "Vulica Aziornaia",
    "Vulica Łuhavaia",
    "Vulica Piianerskaia",
    "Vulica Sadovaia",
    "Vulica Nabiarežnaia",
    "Vulica Biarozkavaia",
    "Vulica Lipavaia",
    "Vulica Dubovaia",
    "Vulica Višniovaia",
    "Vulica Kryštalnaia",
    "Vulica Śvietličnaia",
    "Vulica Kazačnaia",
    "Vulica Vilnianskaia",
    "Vulica Traplanskaia",
    "Vulica Barvinok",
    "Vulica Ramonkavaia",
    "Vulica Abłynievaia",
    "Vulica Brusničnaia",
    "Vulica Maładziožavaia",
    "Vulica Piaščanaia",
    "Vulica Vieraśniovaia",
    "Vulica Prypiackaia",
    "Vulica Kaśmičnaia",
    "Vulica Zarečnaia",
    "Vulica Łiasnoha Aziora",
    "Vulica Liscikavaia",
    "Vulica Dziasiataia", 
    "Vulica Mienskaia",
    "Vulica Haradzienskaia",
    "Vulica Bieraściejskaia",
    "Vulica Viciebskaia",
    "Vulica Mahiloŭskaia",
    "Vulica Homielskaia",
    "Vulica Połackaia",
    "Vulica Navapołackaia",
    "Vulica Lidzkaia",
    "Vulica Maładečanskaia",
    "Vulica Słonimskaia",
    "Vulica Barysaŭskaia",
    "Vulica Mazyrskaia",
    "Vulica Pinskaia",
    "Vulica Smarhonskaia",
    "Vulica Žłobinskaia",
    "Vulica Žodzinskaia",
    "Vulica Rečyckaia",
    "Vulica Kobrynskaia",
    "Vulica Słuckaia",
    "Vulica Babrujskaia",
    "Vulica Niaśvižskaia",
    "Vulica Turaŭskaia",
    "Vulica Barysłaŭskaia",
    "Vulica Łuckaia",
    "Vulica Lvoŭskaia",
    "Vulica Kiieŭskaia",
    "Vulica Charkaŭskaia",
    "Vulica Adeskaia",
    "Vulica Dnieprapiatroŭskaia",
    "Vulica Vinnickaia",
    "Vulica Čarnihaŭskaia",
    "Vulica Žytomirskaia",
    "Vulica Čarkaskaia",
    "Vulica Lvoŭskaia",
    "Vulica Varšaŭskaia",
    "Vulica Krakaŭskaia",
    "Vulica Łiublinskaia",
    "Vulica Toruńskaia",
    "Vulica Biełastockaia",
    "Vulica Zialonaharaskaia",
    "Vulica 25 Sakavika",
    "Vulica 27 Lipienia",
    "Vulica Słuckaha paŭstańnia",
    "Vulica Bieraściejskaj unii",
    "Vulica Łiublinskaj unii",
    "Vulica Hrunvaldzkaj bitvy",
    "Vulica Aršanskaj bitvy",
    "Vulica Bitvy pad Voršaj",
    "Vulica Kreŭskaj unii",
    "Vulica Haradzielskaj unii",
}
end
